- name: Restart grafana-agent
  ansible.builtin.systemd:
    name: grafana-agent
    state: restarted
    daemon_reload: true

- name: Remove grafana-agent temp
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/grafana-agent.zip
    - /tmp/grafana-agent-linux-amd64

