---
# Logrotate role: installs logrotate and deploys configs

- name: Ensure logrotate package is installed
  apt:
    name: logrotate
    state: present
    update_cache: yes
  when: logrotate_enabled
  ignore_errors: true
  changed_when: false

- name: Ensure logrotate config directory exists
  file:
    path: "{{ logrotate_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: logrotate_enabled
  ignore_errors: true

- name: Skip if no logrotate items defined
  debug:
    msg: "No logrotate_items defined, nothing to do"
  when:
    - logrotate_enabled
    - logrotate_items is not defined or logrotate_items | length == 0

- name: Deploy logrotate configuration files
  template:
    src: logrotate_item.j2
    dest: "{{ logrotate_config_dir }}/{{ item.name }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ logrotate_items }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - logrotate_enabled
    - logrotate_items is defined
    - logrotate_items | length > 0
  ignore_errors: true
