- name: Check if role is enabled
  ansible.builtin.debug:
    msg: "Grafana Agent role is disabled or missing config. Skipping."
  when: not agent_enabled
  tags: skip

- name: Ensure required variables are set
  ansible.builtin.assert:
    that:
      - grafana_agent_url is defined
      - prometheus_remote_write_url is defined
      - loki_push_url is defined
    fail_msg: "Missing one or more required variables for Grafana Agent."

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ grafana_agent_config_path }}"
    - "{{ grafana_agent_data_path }}"

- name: Download Grafana Agent zip
  ansible.builtin.get_url:
    url: "{{ grafana_agent_url }}"
    dest: /tmp/grafana-agent.zip
    mode: '0644'

- name: Extract Grafana Agent binary
  ansible.builtin.unarchive:
    src: /tmp/grafana-agent.zip
    dest: /tmp/
    remote_src: true

- name: Move Grafana Agent binary to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/grafana-agent-linux-amd64
    dest: /usr/local/bin/grafana-agent
    remote_src: true
    mode: '0755'

- name: Deploy Grafana Agent config
  ansible.builtin.template:
    src: agent-config.yml.j2
    dest: "{{ grafana_agent_config_file }}"
    mode: '0644'
  notify: Restart grafana-agent

- name: Install Grafana Agent systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/grafana-agent.service
    content: |
      [Unit]
      Description=Grafana Agent
      After=network.target

      [Service]
      ExecStart={{ grafana_agent_binary_path }} --config.file {{ grafana_agent_config_file }}
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify: Restart grafana-agent

- name: Enable and start grafana-agent
  ansible.builtin.systemd:
    name: grafana-agent
    enabled: true
    state: started
    daemon_reload: true
  notify: Remove grafana-agent temp

- name: "Verify Grafana Agent is active and healthy"
  block:
    - name: "Check grafana-agent systemd service is active"
      ansible.builtin.systemd:
        name: grafana-agent
        enabled: true
        state: started
      register: agent_service
      failed_when: agent_service.status.ActiveState != "active"

    - name: "Check grafana-agent /metrics endpoint"
      ansible.builtin.uri:
        url: "http://localhost:12345/metrics"
        method: GET
        status_code: 200
        return_content: false
        timeout: 5
      register: agent_http_check
      failed_when: agent_http_check.status != 200
      ignore_errors: false

    - name: "Grafana Agent is running and responding"
      ansible.builtin.debug:
        msg: "Grafana Agent is active and HTTP endpoint is OK"
  rescue:
    - name: "⚠️ Grafana Agent failed final health check"
      ansible.builtin.debug:
        msg: "Grafana Agent is not running or not responding on port 12345"
      failed_when: true


