- name: Check if Maldet should be installed
  ansible.builtin.debug:
    msg: "⚠️  Skipping Maldet setup because maldet_enabled is false"
  when: not maldet_enabled
  tags: [maldet]

- name: Ensure dependencies for Maldet are installed
  ansible.builtin.package:
    name:
      - wget
      - tar
    state: present
  when: maldet_enabled
  tags: [maldet]

- name: Download Maldet
  ansible.builtin.get_url:
    url: https://www.rfxn.com/downloads/maldetect-current.tar.gz
    dest: "{{ maldet_download_path }}"
    mode: '0644'
  when: maldet_enabled
  tags: [maldet]


- name: Extract Maldet
  ansible.builtin.unarchive:
    src: "{{ maldet_download_path }}"
    dest: /tmp/
    remote_src: yes
  when: maldet_enabled
  tags: [maldet]

- name: Find extracted Maldet directory
  ansible.builtin.find:
    paths: /tmp/
    patterns: "maldetect-*"
    file_type: directory
  register: maldet_extracted
  when: maldet_enabled
  tags: [maldet]

- name: Install Maldet
  ansible.builtin.command:
    cmd: ./install.sh
    chdir: "{{ maldet_extracted.files[0].path }}"
    creates: /usr/local/maldetect/maldet
  when: maldet_enabled and maldet_extracted.files | length > 0
  tags: [maldet]


- name: Configure Maldet (optional)
  ansible.builtin.lineinfile:
    path: /usr/local/maldetect/conf.maldet
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    backup: yes
  loop:
    - { key: "email_alert", value: "{{ '1' if maldet_email_alert else '0' }}" }
    - { key: "email_addr",  value: "{{ maldet_email_address }}" }
    - { key: "quar_hits",   value: "{{ '1' if maldet_quarantine_hits else '0' }}" }
  when: maldet_enabled
  tags: [maldet]

- name: Create cron job for daily scans (if enabled)
  ansible.builtin.cron:
    name: "Maldet Daily Scan"
    job: "/usr/local/maldetect/maldet --scan-all {{ maldet_scan_paths | join(' ') }}"
    user: root
    minute: "0"
    hour: "2"
  when:
    - maldet_enabled
    - maldet_daily_cron | bool
  tags: [maldet]

- name: Remove Maldet cron if disabled
  ansible.builtin.cron:
    name: "Maldet Daily Scan"
    state: absent
  when:
    - maldet_enabled
    - not maldet_daily_cron | bool
  tags: [maldet]
