---
- name: "skip blackbox_exporter if disabled"
  meta: end_host
  when: not (blackbox_exporter_enabled | bool)

- name: fetch blackbox_exporter
  ansible.builtin.get_url:
    url: "{{ blackbox_exporter_url }}"
    dest: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.tar.gz"
    mode: 0644

- name: unpack blackbox_exporter
  ansible.builtin.unarchive:
    src: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.tar.gz"
    dest: "{{ blackbox_exporter_install_dir }}"
    remote_src: yes
    extra_opts: [ "--strip-components=1" ]

- name: install blackbox_exporter binary
  ansible.builtin.file:
    src: "{{ blackbox_exporter_install_dir }}/blackbox_exporter"
    dest: /usr/local/bin/blackbox_exporter
    state: link

- name: write blackbox modules config
  ansible.builtin.copy:
    dest: /etc/blackbox_exporter.yml
    content: |
      modules:
      {%- for name,module in blackbox_modules.items() %}
        {{ name }}:
          prober: {{ module.prober }}
          timeout: "{{ module.timeout }}"
      {%- endfor %}

- name: create systemd unit for blackbox_exporter
  ansible.builtin.copy:
    dest: /etc/systemd/system/blackbox_exporter.service
    content: |
      [Unit]
      Description=Prometheus Blackbox Exporter
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/blackbox_exporter --config.file=/etc/blackbox_exporter.yml --web.listen-address=:{{ blackbox_exporter_port }}
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
  notify: reload systemd

- name: ensure blackbox_exporter is running
  ansible.builtin.systemd:
    name: blackbox_exporter
    enabled: true
    state: started
