# whether to run this role
ufw_enabled: true

# if true, run `ufw reset` first
ufw_reset: false

# default policies
ufw_default_incoming_policy: deny    # deny all incoming by default
ufw_default_outgoing_policy: allow   # allow all outgoing by default

# which TCP ports to allow
ufw_allowed_tcp_ports:
  - "{{ ssh_port | default(22) }}"
  - 80
  - 443

# which UDP ports to allow
ufw_allowed_udp_ports: []

# which TCP ports to explicitly deny
ufw_denied_tcp_ports: []

# which UDP ports to explicitly deny
ufw_denied_udp_ports: []

# extra ports to remove when lockdown is true
ufw_lockdown: false

# enable logging ('on', 'off', 'low', 'high', etc)
ufw_logging: on
