loki_enabled: true
loki_url: "https://github.com/grafana/loki/releases/download/v3.5.0/loki-linux-amd64.zip"

loki_http_port: 3100
loki_grpc_port: 9095

loki_config: |
  auth_enabled: false

  server:
    http_listen_port: {{ loki_http_port }}
    grpc_listen_port: {{ loki_grpc_port }}

  common:
    path_prefix: /opt/loki
    replication_factor: 1
    ring:
      kvstore:
        store: inmemory

  schema_config:
    configs:
      - from: 2022-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  ruler:
    storage:
      type: local
      local:
        directory: /opt/loki/rules
    rule_path: /opt/loki/rules-temp
    alertmanager_url: http://localhost:9093
    ring:
      kvstore:
        store: inmemory
    enable_api: true

  limits_config:
    reject_old_samples: true
    reject_old_samples_max_age: 168h
