- name: Reload systemd
  ansible.builtin.command: systemctl daemon-reload
  changed_when: true

- name: Restart maldet
  ansible.builtin.systemd:
    name: maldet
    enabled: true
    state: restarted
