---
# whether to run this role
prometheus_enabled: true

# which version of Prometheus to install
prometheus_version: "2.46.0"

# download URL for the official Prometheus release tarball
prometheus_download_url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz

# where to install Prometheus
prometheus_install_dir: "/opt/prometheus-{{ prometheus_version }}"

# where to put config & rules
prometheus_config_dir: "/etc/prometheus"

# where Prometheus will store its TSDB
prometheus_data_dir: "/var/lib/prometheus"

# system user/group for the Prometheus process
prometheus_user: prometheus
prometheus_group: prometheus

# minimal scrape interval
prometheus_global_scrape_interval: "15s"

# scrape jobs
# prometheus_scrape_configs:
#   - job_name: prometheus
#     static_configs:
#       - targets: ["localhost:9091"]

prometheus_listen_address: "0.0.0.0"
prometheus_port: 9091

prometheus_scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:{{ prometheus_port }}"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:{{ node_exporter_port }}"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["localhost:{{ cadvisor_port }}"]

  - job_name: "blackbox_http"
    metrics_path: /probe
    params:
      module: ["http_2xx"]
    static_configs:
      - targets:
          - "http://localhost:{{ ssh_port }}"
          - "http://localhost:{{ prometheus_port }}"
    relabel_configs:
      - source_labels: ["__address__"]
        target_label: __param_target
      - source_labels: ["__param_target"]
        target_label: instance
      - target_label: "__address__"
        replacement: "localhost:9115"

  - job_name: "alertmanager"
    static_configs:
      - targets: ["localhost:{{ alertmanager_port }}"]
