# Configures easy access to the server via Cockpit (web UI) and Tailscale (VPN)

- name: 'Access'
  hosts: all
  become: true
  tags: access
  roles:
    - role: tailscale
      tags: [ tailscale, access ]
      when: tailscale_auth_key|default('')|length > 0
    - role: cockpit
      tags: [ cockpit, access ]
    
