---
- name: Getting started....!
  hosts: all
  become: true
  vars:
    hostname: "{{ inventory_hostname }}"
    user_name: alicia
    new_user: alicia
    user_ssh_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    srv_owner: alicia
    srv_group: alicia
    password: "{{ user_password | password_hash('sha512') }}"
    docker_users:
      - alicia

  pre_tasks:
    - name: Ensure Python is available
      raw: test -e /usr/bin/python3 || (apt update && apt install -y python3)
      changed_when: false

    - name: Warn if user_password is not set
      ansible.builtin.debug:
        msg: |
          ⚠️ WARNING: 'user_password' is not defined!
          User {{ new_user }} will not be able to use sudo without a password.
          SSH root login will not be disabled until this is fixed.
      when: user_password is not defined

- import_playbook: essentials.yml
- import_playbook: configs.yml
- import_playbook: backups.yml
- import_playbook: access.yml
- import_playbook: services.yml
- import_playbook: security.yml

- name: Check if user can connect with Ansible
  hosts: all
  gather_facts: true
  become: false
  remote_user: "{{ new_user }}"
  tasks:
    - name: Confirm login is working and set user_ready flag
      set_fact:
        user_ready: true
