- name: Install and configure Docker
  hosts: servers
  become: true
  vars:
    docker_users:
      - alicia
    docker_install_compose_plugin: true
    docker_daemon_options:
      log-opts:
        max-size: "100m"
      storage-driver: "overlay2"
  roles:
    - geerlingguy.docker

- name: Install docker Python module
  hosts: servers
  become: true
  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
