# Configures detailed logging, metrics and monitoring for all processes 
- name: 'Monitoring'
  hosts: all
  become: true
  tags: monitoring
  roles:
    - role: monit
      tags: [ monit, monitoring ]
      ignore_errors: true
      
    - role: logrotate
      tags: [ logrotate, monitoring ]
      ignore_errors: true

    - role: loki
      tags: [ loki, monitoring ]
      ignore_errors: true

    - role: grafana-agent
      tags: [ grafana-agent, monitoring ]
      ignore_errors: true

    - role: blackbox_exporter
      tags: [ blackbox_exporter, monitoring ]
      ignore_errors: true

    - role: node_exporter
      tags: [ node_exporter, monitoring ]
      ignore_errors: true

    - role: prometheus
      tags: [ prometheus, monitoring ]
      ignore_errors: true

    - role: grafana
      tags: [ grafana, monitoring ]
      ignore_errors: true
