# Properly secures the system with DevSec best practices, for example:
# - System hardening (CIS benchmarks)
# - Process confinement (AppArmour)
# - Intrusion detection (Fail2Ban),
# - Integrity monitoring (OSSEC)
# - Malware scanning (Maldet)
# - Automated security audits (Lynis)
- name: 'Security'
  hosts: all
  become: true
  tags: security

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
      tags: always
  tasks:
    - name: Include fail2ban role
      ansible.builtin.include_role:
        name: fail2ban
        apply:
          tags: [fail2ban]
      when: fail2ban_enabled | default(true)
      tags: [fail2ban]
      ignore_errors: true  # noqa ignore-errors

    - name: Include maldet role
      ansible.builtin.include_role:
        name: maldet
        apply:
          tags: [maldet]
      when: maldet_enabled | default(true)
      tags: [maldet]
      ignore_errors: true  # noqa ignore-errors

    - name: Include lynis role
      ansible.builtin.include_role:
        name: lynis
        apply:
          tags: [lynis]
      when: lynis_enabled | default(true)
      tags: [lynis]
      ignore_errors: true  # noqa ignore-errors

    - name: Include apparmor role
      ansible.builtin.include_role:
        name: apparmor
      vars:
        run_scan: true  # noqa: var-naming[no-role-prefix]
      when: apparmor_enabled | default(true)
      tags: [apparmor]
      ignore_errors: true  # noqa ignore-errors

    - name: Include unattended-upgrades role
      ansible.builtin.include_role:
        name: unattended-upgrades
        apply:
          tags: [unattended-upgrades]
      when: unattended_upgrades_enabled | default(true)
      tags: [unattended-upgrades]
      ignore_errors: true  # noqa ignore-errors
