# - name: Update & Upgrade all packages
#   hosts: servers
#   become: true
#   tasks:
#     - name: Update APT cache
#       apt:
#         update_cache: yes
#         cache_valid_time: 3600

#     - name: Upgrade packages
#       apt:
#         upgrade: dist
#         autoremove: yes
